steps:
  - id: "terraform init"
    name: "hashicorp/terraform:latest"
    args: ["-chdir=${_CHDIR}", "init", "-no-color"]
  - id: "terraform apply"
    name: "hashicorp/terraform:latest"
    args: ["-chdir=${_CHDIR}", "apply", "-auto-approve", "-no-color"]

options:
  logging: "CLOUD_LOGGING_ONLY"

substitutions:
  _CHDIR: ""